scrape_configs:
  - job_name: grafana
    metrics_path: /grafana/metrics
    dns_sd_configs:
      - names: [ 'grafana' ]
        type: 'A'
        port: 3000
    relabel_configs:
      - source_labels: [ '__meta_dns_name' ]
        target_label: 'service'
