scrape_configs:
  - job_name: prometheus
    metrics_path: /prometheus/metrics
    dns_sd_configs:
      - names: [ 'prometheus' ]
        type: 'A'
        port: 9090
    relabel_configs:
      - source_labels: [ '__meta_dns_name' ]
        target_label: 'service'
