global:
  # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  scrape_interval: 15s

  # Evaluate rules every 15 seconds. The default is every 1 minute.
  evaluation_interval: 15s
scrape_config_files: [ '/etc/prometheus/targets/*.yaml' ]
scrape_configs:
  - job_name: grafana
    metrics_path: /grafana/metrics
    dns_sd_configs:
      - names: [ 'grafana' ]
        type: 'A'
        port: 3000
    relabel_configs:
      - source_labels: [ '__meta_dns_name' ]
        target_label: 'service'

  - job_name: caddy
    dns_sd_configs:
      - names: [ 'caddy' ]
        type: 'A'
        port: 2019
    relabel_configs:
      - source_labels: [ '__meta_dns_name' ]
        target_label: 'service'

  - job_name: iss_exporter
    scrape_interval: 2s
    dns_sd_configs:
      - names: [ 'exporter' ]
        type: 'A'
        port: 3000
    relabel_configs:
      - source_labels: [ '__meta_dns_name' ]
        target_label: 'service'
