{
 "title": "ISS Telemetry",
 "description": "Live Telemetry data from the ISS!",
 "tags": [
  "iss",
  "telemetry"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "prometheus", "label": "Prometheus Instance", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Current Position", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ISS Station Mode",
   "type": "stat",
   "description": "ISS Station Mode - 1=Standard\n2=Microgravity\n4=Reboost\n8=Proximity_Ops\n16=External_Ops\n32=Survival\n64=ASCR\n127=all_modes",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iss_odin_vvo_uslab000086", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current Location",
   "type": "geomap",
   "gridPos": { "h": 12, "w": 12, "x": 4, "y": 1 },
   "targets": [
    { "expr": "iss_position_latitude   ", "legendFormat": "latitude" },
    { "expr": "iss_position_longitude", "legendFormat": "longitude" },
    { "expression": "Latitude", "reducer": "last", "type": "reduce" },
    { "expression": "Longitude", "reducer": "last", "type": "reduce" }
   ]
  },
  { "title": "ISS News Feed", "type": "news", "gridPos": { "h": 12, "w": 8, "x": 16, "y": 1 } },
  {
   "title": "Attitude Maneuver in Progress",
   "type": "stat",
   "description": "Attitude Maneuver In Progress status",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iss_vvo_uslab000081", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Mass",
   "type": "stat",
   "description": "ISS Total Mass (kg)",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "masst" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iss_adco_uslab000039 / 1000", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Onboard Time",
   "type": "stat",
   "description": "ISS Command and Control Multiplexer/Demultiplexer Onboard Time (fine)",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iss_odin_uslab000084 * 1000", "legendFormat": "__auto" }
   ]
  },
  { "title": "ETHOS: Life Support", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Cabin pressure",
   "type": "timeseries",
   "description": "Cabin pressure",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "pressurepsi" } },
   "targets": [
    { "expr": "iss_ethos_uslab000058", "legendFormat": "Cabin Pressure" }
   ]
  },
  {
   "title": "Cabin temperature",
   "type": "timeseries",
   "description": "Cabin temperature",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "iss_ethos_uslab000059", "legendFormat": "Cabin temperature" }
   ]
  },
  {
   "title": "Oxygen Generator State",
   "type": "stat",
   "description": "Oxygen Generator State",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iss_ethos_node3000010", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Water Processor State",
   "type": "stat",
   "description": "Water Processor State",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iss_ethos_node3000006", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Water Processor State",
   "type": "stat",
   "description": "Water Processor State",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iss_ethos_node3000007", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Urine Processor State",
   "type": "stat",
   "description": "Urine Processor State",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iss_ethos_node3000004", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "O₂ Production rate",
   "type": "timeseries",
   "description": "O₂ Production rate",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "lbm/d" } },
   "targets": [
    { "expr": "iss_ethos_node3000011", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Water Tank Fill Level",
   "type": "gauge",
   "description": "Waste Water Tank Qty",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iss_ethos_node3000008", "legendFormat": "Waste Water" },
    { "expr": "iss_ethos_node3000009", "legendFormat": "Clean Water" }
   ]
  },
  {
   "title": "Urine Tank Fill Level",
   "type": "gauge",
   "description": "Urine Tank Qty",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iss_ethos_node3000005", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Air Conditioner State",
   "type": "stat",
   "description": "Air Conditioner State",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iss_ethos_node2000003", "legendFormat": "Node 2" },
    { "expr": "iss_ethos_node3000018", "legendFormat": "Node 3" },
    { "expr": "iss_ethos_uslab000064", "legendFormat": "Lab, Port" },
    { "expr": "iss_ethos_uslab000065", "legendFormat": "Lab, Starboard" },
    { "expr": "iss_ethos_airlock000053", "legendFormat": "Airlock" }
   ]
  },
  {
   "title": "Vacuum System Valves",
   "type": "stat",
   "description": "VRS Vent Valve Position\nVES Vent Valve Position",
   "gridPos": { "h": 8, "w": 4, "x": 6, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iss_ethos_uslab000062",
     "legendFormat": "Vacuum Resource System Valve Position"
    },
    {
     "expr": "iss_ethos_uslab000063",
     "legendFormat": "Vacuum Exhaust System Valve Position"
    }
   ]
  },
  {
   "title": "Atmospheric Composition: Node 3",
   "type": "timeseries",
   "description": "MCA Partial Pressure in PSIA",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "pressurepsi" } },
   "targets": [
    { "expr": "iss_ethos_node3000003", "legendFormat": "CO₂" },
    { "expr": "iss_ethos_node3000001", "legendFormat": "O₂" },
    { "expr": "iss_ethos_node3000002", "legendFormat": "N₂" }
   ]
  },
  {
   "title": "Atmospheric Composition: Lab",
   "type": "timeseries",
   "description": "MCA Partial Pressure in PSIA",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "pressurepsi" } },
   "targets": [
    { "expr": "iss_ethos_uslab000055", "legendFormat": "CO₂" },
    { "expr": "iss_ethos_uslab000053", "legendFormat": "O₂" },
    { "expr": "iss_ethos_uslab000054", "legendFormat": "N₂" }
   ]
  },
  {
   "title": "SPARTAN: Photovoltaics, Heat Radiators",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 }
  },
  {
   "title": "TRRJ/SARJ Positions",
   "type": "gauge",
   "description": "Starboard Thermal Radiator Rotating Joint (TRRJ) Position (degrees),\nPort Thermal Radiator Rotating Joint (TRRJ) Position (degrees),\nSolar Alpha Rotary Joint (SARJ) Starboard Joint Angle Position (degrees),\nSolar Alpha Rotary Joint (SARJ) Port Joint Angle Position (degrees)",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iss_spartan_vvo_s0000001",
     "legendFormat": "Starboard Thermal Radiator Rotating Joint (TRRJ)"
    },
    {
     "expr": "iss_spartan_vvo_s0000002",
     "legendFormat": "Port Thermal Radiator Rotating Joint (TRRJ)"
    },
    {
     "expr": "iss_spartan_vvo_s0000003",
     "legendFormat": "Solar Alpha Rotary Joint (SARJ) Starboard Joint Angle"
    },
    {
     "expr": "iss_spartan_vvo_s0000004",
     "legendFormat": "Solar Alpha Rotary Joint (SARJ) Port Joint Angle"
    }
   ]
  },
  {
   "title": "Photovolatic Control Unit (PVCU): Gimble Position",
   "type": "gauge",
   "description": "Photovolatic Control Unit (PVCU) - Solar Array - Beta Gimble Assembly (BGA) Position (degrees)",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iss_spartan_s4000007", "legendFormat": "Solar Array 1A" },
    { "expr": "iss_spartan_p4000007", "legendFormat": "Solar Array 2A" },
    { "expr": "iss_spartan_s4000008", "legendFormat": "Solar Array 3A" },
    { "expr": "iss_spartan_p4000008", "legendFormat": "Solar Array 4A" },
    { "expr": "iss_spartan_s6000008", "legendFormat": "Solar Array 1B" },
    { "expr": "iss_spartan_p6000008", "legendFormat": "Solar Array 2B" },
    { "expr": "iss_spartan_s6000007", "legendFormat": "Solar Array 3B" },
    { "expr": "iss_spartan_p6000007", "legendFormat": "Solar Array 4B" }
   ]
  },
  {
   "title": "Solar Beta Angle",
   "type": "gauge",
   "description": "Solar Beta Angle (degrees",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iss_adco_uslab000040", "legendFormat": "Solar Beta Angle" }
   ]
  },
  {
   "title": "SARJ Port Joint Angle: Commanded Position",
   "type": "gauge",
   "description": "Solar Alpha Rotary Joint (SARJ) Port Joint Angle Commanded Position",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iss_vvo_s0000005",
     "legendFormat": "Solar Alpha Rotary Joint (SARJ) Port Joint Angle Commanded Position"
    }
   ]
  },
  {
   "title": "TRRJ/SARJ Positions",
   "type": "timeseries",
   "description": "Starboard Thermal Radiator Rotating Joint (TRRJ) Position (degrees),\nPort Thermal Radiator Rotating Joint (TRRJ) Position (degrees),\nSolar Alpha Rotary Joint (SARJ) Starboard Joint Angle Position (degrees),\nSolar Alpha Rotary Joint (SARJ) Port Joint Angle Position (degrees)",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "expr": "iss_spartan_vvo_s0000001",
     "legendFormat": "Starboard Thermal Radiator Rotating Joint (TRRJ)"
    },
    {
     "expr": "iss_spartan_vvo_s0000002",
     "legendFormat": "Port Thermal Radiator Rotating Joint (TRRJ)"
    },
    {
     "expr": "iss_spartan_vvo_s0000003",
     "legendFormat": "Solar Alpha Rotary Joint (SARJ) Starboard Joint Angle"
    },
    {
     "expr": "iss_spartan_vvo_s0000004",
     "legendFormat": "Solar Alpha Rotary Joint (SARJ) Port Joint Angle"
    }
   ]
  },
  {
   "title": "Photovolatic Control Unit (PVCU): Gimble Position",
   "type": "timeseries",
   "description": "Photovolatic Control Unit (PVCU) - Solar Array - Beta Gimble Assembly (BGA) Position (degrees)",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    { "expr": "iss_spartan_s4000007", "legendFormat": "Solar Array 1A" },
    { "expr": "iss_spartan_p4000007", "legendFormat": "Solar Array 2A" },
    { "expr": "iss_spartan_s4000008", "legendFormat": "Solar Array 3A" },
    { "expr": "iss_spartan_p4000008", "legendFormat": "Solar Array 4A" },
    { "expr": "iss_spartan_s6000008", "legendFormat": "Solar Array 1B" },
    { "expr": "iss_spartan_p6000008", "legendFormat": "Solar Array 2B" },
    { "expr": "iss_spartan_s6000007", "legendFormat": "Solar Array 3B" },
    { "expr": "iss_spartan_p6000007", "legendFormat": "Solar Array 4B" }
   ]
  },
  {
   "title": "Solar Beta Angle",
   "type": "timeseries",
   "description": "Solar Beta Angle (degrees",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    { "expr": "iss_adco_uslab000040", "legendFormat": "Solar Beta Angle" }
   ]
  },
  {
   "title": "SARJ Port Joint Angle: Commanded Position",
   "type": "timeseries",
   "description": "Solar Alpha Rotary Joint (SARJ) Port Joint Angle Commanded Position",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "expr": "iss_vvo_s0000005",
     "legendFormat": "Solar Alpha Rotary Joint (SARJ) Port Joint Angle Commanded Position"
    }
   ]
  },
  {
   "title": "Photovolatic Control Unit (PVCU): Drive Voltage",
   "type": "timeseries",
   "description": "Photovolatic Control Unit (PVCU) - Solar Array - Drive Voltage",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "iss_spartan_s4000001", "legendFormat": "Solar Array 1A" },
    { "expr": "iss_spartan_p4000001", "legendFormat": "Solar Array 2A" },
    { "expr": "iss_spartan_p4000004", "legendFormat": "Solar Array 4A" },
    { "expr": "iss_spartan_s6000004", "legendFormat": "Solar Array 1B" },
    { "expr": "iss_spartan_p6000004", "legendFormat": "Solar Array 2B" },
    { "expr": "iss_spartan_s4000001", "legendFormat": "Solar Array 3B" },
    { "expr": "iss_spartan_p6000001", "legendFormat": "Solar Array 4B" }
   ]
  },
  {
   "title": "ECTS: TRRJ/SARJ Software Mode",
   "type": "stat",
   "description": "External Thermal Control System (ETCS) - Thermal Radiator Rotating Joint (TRRJ) - Loop B - Software mode\nExternal Thermal Control System (ETCS) - Thermal Radiator Rotating Joint (TRRJ) - Loop A - Software mode\nExternal Primary Solar Alpha Rotary Joint (SARJ) Port Mode\nExternal Primary Solar Alpha Rotary Joint (SARJ) Starboard Mode",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iss_vvo_s0000006", "legendFormat": "TRRJ: Loop B" },
    { "expr": "iss_vvo_s0000007", "legendFormat": "TRRJ: Loop A" },
    { "expr": "iss_vvo_s0000008", "legendFormat": "SARJ: Port" },
    { "expr": "iss_vvo_s0000009", "legendFormat": "SRJ: Starboard" }
   ]
  },
  { "title": "ETHOS: Cooling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Avionics Cooling Fluid: Temperature",
   "type": "timeseries",
   "description": "Avionics Cooling Fluid Temp",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "iss_ethos_node2000007", "legendFormat": "Node 2" },
    { "expr": "iss_ethos_node3000012", "legendFormat": "Node 3" },
    { "expr": "iss_ethos_uslab000060", "legendFormat": "Lab" }
   ]
  },
  {
   "title": "Air Cooling Fluid: Temperature",
   "type": "timeseries",
   "description": "Air Cooling Fluid Temp",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "iss_ethos_node2000006", "legendFormat": "Node 2" },
    { "expr": "iss_ethos_node3000013", "legendFormat": "Node 3" },
    { "expr": "iss_ethos_uslab000061", "legendFormat": "Lab" }
   ]
  },
  {
   "title": "Coolant Water: Quantity",
   "type": "timeseries",
   "description": "Coolant water quantity",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "targets": [
    { "expr": "iss_ethos_node2000001", "legendFormat": "Node 2, MT" },
    { "expr": "iss_ethos_node2000002", "legendFormat": "Node 2, LT" },
    { "expr": "iss_ethos_node3000019", "legendFormat": "Node 3" },
    { "expr": "iss_ethos_uslab000056", "legendFormat": "Lab, LT" },
    { "expr": "iss_ethos_uslab000057", "legendFormat": "Lab, MT" }
   ]
  },
  { "title": "ETHOS: Airlock", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "Crewlock Pressure",
   "type": "timeseries",
   "description": "EVAS AL CL Sensor Pressure",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "mmHg" } },
   "targets": [
    { "expr": "iss_ethos_airlock000049", "legendFormat": "Crewlock Pressure" }
   ]
  },
  {
   "title": "Airlock Pressure",
   "type": "timeseries",
   "description": "PCA Cabin Pressure",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "pressurepsi" } },
   "targets": [
    { "expr": "iss_ethos_airlock000054", "legendFormat": "Airlock Cabin Pressure" }
   ]
  },
  {
   "title": "Airlock Gas Tank Pressure",
   "type": "timeseries",
   "description": "ACS AL N2 #1 Line Pressure Sensor Data\nACS AL O2 #2 Line Pressure Sensor Data\nACS AL O2 #3 Line Pressure Sensor Data",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "count:mmHg" } },
   "targets": [
    { "expr": "iss_ethos_airlock000055", "legendFormat": "O₂ Tank: High Pressure" },
    { "expr": "iss_ethos_airlock000056", "legendFormat": "O₂ Tank: Low Pressure" },
    { "expr": "iss_ethos_airlock000057", "legendFormat": "N₂ Tank: Pressure" }
   ]
  },
  {
   "title": "Airlock Pressure Valves",
   "type": "stat",
   "description": "ACS AL High Pressure O2 Supply Valve Actual Position\nACS AL Low Pressure O2 Supply Valve Actual Position\nACS AL Low Pressure N2 Supply Valve Actual Position",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iss_ethos_airlock000052", "legendFormat": "N₂ Supply Valve Position" },
    { "expr": "iss_ethos_airlock000051", "legendFormat": "Low pO₂ Supply valve position" },
    { "expr": "iss_ethos_airlock000050", "legendFormat": "High pO₂ Supply valve position" }
   ]
  },
  { "title": "ADCO: Attitude", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 } },
  {
   "title": "US Attitude Source",
   "type": "stat",
   "description": "US Attitude Source:\n0: NONE\n1: GPS1\n2: GPS2\n3: Russian_Attitude\n4: Ku_Band",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 100 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iss_adco_uslab000013", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "US State Vector Source",
   "type": "stat",
   "description": "US State Vector Source:\n0: No Source\n1: Unused\n2: Unused\n3: Russian\n4: GPS1 Deterministic\n5: GPS2 Deterministic\n6: Ground",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 100 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iss_adco_uslab000015", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Attitude Control Reference Frame",
   "type": "stat",
   "description": "Attitude Controller Type:\n0: LVLH\n1: Inertial\n2: XPOP",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 100 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iss_adco_uslab000016", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CMG Attitude Alarm",
   "type": "stat",
   "description": "Loss of CMG Attitude Control (LOAC) Caution Message In Alarm",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 100 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iss_adco_uslab000041", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GPS 1: Status",
   "type": "stat",
   "description": "Global Positioning System (GPS-1) Ops Status",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 100 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iss_adco_uslab000043", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "US Rate Source",
   "type": "stat",
   "description": "US Rate Source:\n0: None\n1: RGA 1\n2: RGA 2\n3: Russian",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 104 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iss_adco_uslab000014", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Attitude Controller Type",
   "type": "stat",
   "description": "Attitude Controller Type:\n0: Attitude Hold\n1: TEA",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 104 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iss_adco_uslab000016", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "ISS Attitude Alarm",
   "type": "stat",
   "description": "Loss of ISS Attitude Control (LOAC) Caution Message In Alarm",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 104 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iss_adco_uslab000042", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GPS 2: Status",
   "type": "stat",
   "description": "Global Positioning System (GPS-2) Ops Status",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 104 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iss_adco_uslab000044", "legendFormat": "__auto" }
   ]
  },
  { "title": "ADCO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 } },
  {
   "title": "Control Moment Gyroscope",
   "type": "stat",
   "description": "Control Moment Gyroscope Online Status",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iss_adco_uslab000001", "legendFormat": "CMG-1" },
    { "expr": "iss_adco_uslab000002", "legendFormat": "CMG-2" },
    { "expr": "iss_adco_uslab000003", "legendFormat": "CMG-3" },
    { "expr": "iss_adco_uslab000004", "legendFormat": "CMG-4" }
   ]
  },
  {
   "title": "Desaturation Request",
   "type": "stat",
   "description": "Desaturation Request (Enabled/Inhibited)",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iss_adco_uslab000011", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Control Moment Gyroscope: Control Torque",
   "type": "timeseries",
   "description": "Control Moment Gyroscope (CMG) Control Torque - Roll (N-m)\nControl Moment Gyroscope (CMG) Control Torque - Pitch (N-m)\nControl Moment Gyroscope (CMG) Control Torque - Yaw (N-m)",
   "gridPos": { "h": 9, "w": 9, "x": 6, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "forceNm" } },
   "targets": [
    { "expr": "iss_adco_uslab000006", "legendFormat": "Roll" },
    { "expr": "iss_adco_uslab000007", "legendFormat": "Pitch" },
    { "expr": "iss_adco_uslab000008", "legendFormat": "Yaw" }
   ]
  },
  {
   "title": "Active Control Moment Gyroscope: Momentum",
   "type": "timeseries",
   "description": "Active Control Moment Gyroscope (CMG) Momentum (Nms)",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "Nm/s" } },
   "targets": [
    { "expr": "iss_adco_uslab000009", "legendFormat": "Momentum" }
   ]
  },
  { "title": "ODIN", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 118 } },
  {
   "title": "Data Load Command Counter",
   "type": "stat",
   "description": "Data Load Command Counter - Count of data load commands received by the ISS Command and Control Computer",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iss_odin_uslab000083", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Data Load Command Counter",
   "type": "stat",
   "description": "Data Load Command Counter - Count of data load commands received by the ISS Command and Control Computer",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iss_odin_uslab000083", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active Laptops",
   "type": "stat",
   "description": "Laptops active and connected to the Primary Command and Control (C&C) Multiplexer/Demultiplexer (MDM)",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iss_odin_uslab000087", "legendFormat": "__auto" }
   ]
  },
  { "title": "EVA", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 122 } },
  {
   "title": "Spacesuit Power: Voltage",
   "type": "timeseries",
   "description": "Supplies power through the Umbilical Interface Assembly (UIA) to the spacesuits, Voltage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "iss_eva_airlock000007", "legendFormat": "EMU 1" },
    { "expr": "iss_eva_airlock000001", "legendFormat": "EMU 1 (UIA)" },
    { "expr": "iss_eva_airlock000009", "legendFormat": "EMU 2" },
    { "expr": "iss_eva_airlock000003", "legendFormat": "EMU 2 (UIA)" }
   ]
  },
  {
   "title": "Spacesuit Power: Current",
   "type": "timeseries",
   "description": "Supplies power through the Umbilical Interface Assembly (UIA) to the spacesuits, Current",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "iss_eva_airlock000008", "legendFormat": "EMU 1" },
    { "expr": "iss_eva_airlock000002", "legendFormat": "EMU 1 (UIA)" },
    { "expr": "iss_eva_airlock000010", "legendFormat": "EMU 2" },
    { "expr": "iss_eva_airlock000004", "legendFormat": "EMU 2 (UIA)" }
   ]
  },
  {
   "title": "IRU Voltage",
   "type": "timeseries",
   "description": "In-flight Refill Unit (IRU), Voltage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "iss_eva_airlock000005", "legendFormat": "Voltage" }
   ]
  },
  {
   "title": "IRU Current",
   "type": "timeseries",
   "description": "In-flight Refill Unit (IRU), Current",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "iss_eva_airlock000006", "legendFormat": "Current" }
   ]
  },
  {
   "title": "Battery Charger Assembly: Channel Status",
   "type": "stat",
   "description": "Battery Charger Assembly (BCA) Channel Status",
   "gridPos": { "h": 27, "w": 8, "x": 0, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iss_eva_airlock000023", "legendFormat": "BCA 1, Channel 1" },
    { "expr": "iss_eva_airlock000024", "legendFormat": "BCA 1, Channel 2" },
    { "expr": "iss_eva_airlock000025", "legendFormat": "BCA 1, Channel 3" },
    { "expr": "iss_eva_airlock000026", "legendFormat": "BCA 1, Channel 4" },
    { "expr": "iss_eva_airlock000027", "legendFormat": "BCA 1, Channel 5" },
    { "expr": "iss_eva_airlock000028", "legendFormat": "BCA 1, Channel 6" },
    { "expr": "iss_eva_airlock000029", "legendFormat": "BCA 2, Channel 1" },
    { "expr": "iss_eva_airlock000030", "legendFormat": "BCA 2, Channel 2" },
    { "expr": "iss_eva_airlock000031", "legendFormat": "BCA 2, Channel 3" },
    { "expr": "iss_eva_airlock000032", "legendFormat": "BCA 2, Channel 4" },
    { "expr": "iss_eva_airlock000033", "legendFormat": "BCA 2, Channel 5" },
    { "expr": "iss_eva_airlock000034", "legendFormat": "BCA 2, Channel 6" },
    { "expr": "iss_eva_airlock000035", "legendFormat": "BCA 3, Channel 1" },
    { "expr": "iss_eva_airlock000036", "legendFormat": "BCA 3, Channel 2" },
    { "expr": "iss_eva_airlock000037", "legendFormat": "BCA 3, Channel 3" },
    { "expr": "iss_eva_airlock000038", "legendFormat": "BCA 3, Channel 4" },
    { "expr": "iss_eva_airlock000039", "legendFormat": "BCA 3, Channel 5" },
    { "expr": "iss_eva_airlock000040", "legendFormat": "BCA 3, Channel 6" },
    { "expr": "iss_eva_airlock000041", "legendFormat": "BCA 4, Channel 1" },
    { "expr": "iss_eva_airlock000042", "legendFormat": "BCA 4, Channel 2" },
    { "expr": "iss_eva_airlock000043", "legendFormat": "BCA 4, Channel 3" },
    { "expr": "iss_eva_airlock000044", "legendFormat": "BCA 4, Channel 4" },
    { "expr": "iss_eva_airlock000045", "legendFormat": "BCA 4, Channel 5" },
    { "expr": "iss_eva_airlock000046", "legendFormat": "BCA 4, Channel 6" }
   ]
  },
  {
   "title": "Battery Charger Assembly: Voltage",
   "type": "timeseries",
   "description": "Battery Charger Assembly (BCA), Voltage",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "iss_eva_airlock000011", "legendFormat": "BCA 1" },
    { "expr": "iss_eva_airlock000013", "legendFormat": "BCA 2" },
    { "expr": "iss_eva_airlock000015", "legendFormat": "BCA 3" },
    { "expr": "iss_eva_airlock000017", "legendFormat": "BCA 4" }
   ]
  },
  {
   "title": "Battery Charger Assembly: Current",
   "type": "timeseries",
   "description": "Battery Charger Assembly (BCA), Current",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "iss_eva_airlock000012", "legendFormat": "BCA 1" },
    { "expr": "iss_eva_airlock000014", "legendFormat": "BCA 2" },
    { "expr": "iss_eva_airlock000016", "legendFormat": "BCA 3" },
    { "expr": "iss_eva_airlock000018", "legendFormat": "BCA 4" }
   ]
  },
  {
   "title": "Battery Charger Assembly: Status",
   "type": "stat",
   "description": "Battery Charger Assembly (BCA) Status",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iss_eva_airlock000019", "legendFormat": "BCA 1: Status" },
    { "expr": "iss_eva_airlock000020", "legendFormat": "BCA 2: Status" },
    { "expr": "iss_eva_airlock000021", "legendFormat": "BCA 3: Status" },
    { "expr": "iss_eva_airlock000022", "legendFormat": "BCA 4: Status" }
   ]
  },
  { "title": "SPARTAN: Ammonia Pump Module", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 166 } },
  {
   "title": "Pump Flowrate",
   "type": "timeseries",
   "description": "Pump Flowrate (kg/hr)",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 167 },
   "fieldConfig": { "defaults": { "unit": "kg/h" } },
   "targets": [
    { "expr": "iss_spartan_s1000001", "legendFormat": "Loop A" },
    { "expr": "iss_spartan_p1000001", "legendFormat": "Loop B" }
   ]
  },
  {
   "title": "Ammonia Out Pressure",
   "type": "timeseries",
   "description": "PM Out Press (kPa)",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 167 },
   "fieldConfig": { "defaults": { "unit": "pressurekpa" } },
   "targets": [
    { "expr": "iss_spartan_s1000002", "legendFormat": "Loop A" },
    { "expr": "iss_spartan_p1000002", "legendFormat": "Loop B" }
   ]
  },
  {
   "title": "Ammonia Out Temperature",
   "type": "timeseries",
   "description": "PM Out Temp (deg C)",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 167 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "iss_spartan_s1000003", "legendFormat": "Loop A" },
    { "expr": "iss_spartan_p1000003", "legendFormat": "Loop B" }
   ]
  }
 ]
}