{
 "title": "Prometheus",
 "description": "Overview of metrics from Prometheus itself. Useful for using prometheus to monitor your prometheus.",
 "tags": [
  "stack",
  "prometheus",
  "metrics"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": "query_result(prometheus_tsdb_head_samples_appended_total)"
   },
   {
    "name": "instance",
    "query": "query_result(up{job=~\"$job\"})"
   },
   {
    "name": "interval",
    "query": "1h, 3h, 6h, 12h, 1d, 2d, 7d, 30d, 90d, 180d"
   },
   { "name": "prometheus", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Prometheus",
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "Metrics for the Prometheus server. Prometheus collects and stores its metrics as time series data, i.e. metrics information is stored with the timestamp at which it was recorded, alongside optional key-value pairs called labels.\n\n[Prometheus](https://github.com/prometheus) is an open-source systems monitoring and alerting toolkit originally built at [SoundCloud](https://soundcloud.com/). Since its inception in 2012, many companies and organizations have adopted Prometheus, and the project has a very active developer and user [community](https://prometheus.io/community). It is now a standalone open source project and maintained independently of any company. To emphasize this, and to clarify the project's governance structure, Prometheus joined the [Cloud Native Computing Foundation](https://cncf.io/) in 2016 as the second hosted project, after Kubernetes.\n\n\n"
   }
  },
  {
   "title": "At a Glance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime [$interval]",
   "type": "stat",
   "description": "Percentage of uptime during the most recent $interval period.  Change the period with the 'interval' dropdown above.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(up{instance=~\"$instance\",job=~\"$job\"}[$interval]) * 100)"
    }
   ]
  },
  {
   "title": "Currently Down",
   "type": "table",
   "description": "Servers which are DOWN RIGHT NOW! \nFIX THEM!!",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 6 },
   "targets": [
    {
     "expr": "up{instance=~\"$instance\",job=~\"$job\"} < 1"
    }
   ]
  },
  {
   "title": "Total Series",
   "type": "stat",
   "description": "Total number of time series in prometheus",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_series{job=~\"$job\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Memory Chunks",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_chunks{job=~\"$job\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Quick Numbers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Missed Iterations [$interval]",
   "type": "stat",
   "description": "The total number of rule group evaluations missed due to slow rule group evaluation.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(prometheus_evaluator_iterations_missed_total{job=~\"$job\",instance=~\"$instance\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Skipped Iterations [$interval]",
   "type": "stat",
   "description": "The total number of rule group evaluations skipped due to throttled metric storage.",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(prometheus_evaluator_iterations_skipped_total{job=~\"$job\",instance=~\"$instance\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Tardy Scrapes [$interval]",
   "type": "stat",
   "description": "Total number of scrapes that hit the sample limit and were rejected.",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(prometheus_target_scrapes_exceeded_sample_limit_total{job=~\"$job\",instance=~\"$instance\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Reload Failures [$interval]",
   "type": "stat",
   "description": "Number of times the database failed to reload block data from disk.",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(prometheus_tsdb_reloads_failures_total{job=~\"$job\",instance=~\"$instance\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Skipped Scrapes [$interval]",
   "type": "stat",
   "description": "Sum of all skipped scrapes",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(prometheus_target_scrapes_exceeded_sample_limit_total{job=~\"$job\",instance=~\"$instance\"}[$interval])) + \nsum(sum_over_time(prometheus_target_scrapes_sample_duplicate_timestamp_total{job=~\"$job\",instance=~\"$instance\"}[$interval])) + \nsum(sum_over_time(prometheus_target_scrapes_sample_out_of_bounds_total{job=~\"$job\",instance=~\"$instance\"}[$interval])) + \nsum(sum_over_time(prometheus_target_scrapes_sample_out_of_order_total{job=~\"$job\",instance=~\"$instance\"}[$interval])) "
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Failures and Errors",
   "type": "timeseries",
   "description": "All non-zero failures and errors",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(net_conntrack_dialer_conn_failed_total{instance=~\"$instance\"}[5m])) > 0",
     "legendFormat": "Failed Connections"
    },
    {
     "expr": "sum(increase(prometheus_evaluator_iterations_missed_total{instance=~\"$instance\"}[5m])) > 0",
     "legendFormat": "Missed Iterations"
    },
    {
     "expr": "sum(increase(prometheus_evaluator_iterations_skipped_total{instance=~\"$instance\"}[5m])) > 0",
     "legendFormat": "Skipped Iterations"
    },
    {
     "expr": "sum(increase(prometheus_rule_evaluation_failures_total{instance=~\"$instance\"}[5m])) > 0",
     "legendFormat": "Evaluation"
    },
    {
     "expr": "sum(increase(prometheus_sd_azure_refresh_failures_total{instance=~\"$instance\"}[5m])) > 0",
     "legendFormat": "Azure Refresh"
    },
    {
     "expr": "sum(increase(prometheus_sd_consul_rpc_failures_total{instance=~\"$instance\"}[5m])) > 0",
     "legendFormat": "Consul RPC"
    },
    {
     "expr": "sum(increase(prometheus_sd_dns_lookup_failures_total{instance=~\"$instance\"}[5m])) > 0",
     "legendFormat": "DNS Lookup"
    },
    {
     "expr": "sum(increase(prometheus_sd_ec2_refresh_failures_total{instance=~\"$instance\"}[5m])) > 0",
     "legendFormat": "EC2 Refresh"
    },
    {
     "expr": "sum(increase(prometheus_sd_gce_refresh_failures_total{instance=~\"$instance\"}[5m])) > 0",
     "legendFormat": "GCE Refresh"
    },
    {
     "expr": "sum(increase(prometheus_sd_marathon_refresh_failures_total{instance=~\"$instance\"}[5m])) > 0",
     "legendFormat": "Marathon Refresh"
    },
    {
     "expr": "sum(increase(prometheus_sd_openstack_refresh_failures_total{instance=~\"$instance\"}[5m])) > 0",
     "legendFormat": "Openstack Refresh"
    },
    {
     "expr": "sum(increase(prometheus_sd_triton_refresh_failures_total{instance=~\"$instance\"}[5m])) > 0",
     "legendFormat": "Triton Refresh"
    },
    {
     "expr": "sum(increase(prometheus_target_scrapes_exceeded_sample_limit_total{instance=~\"$instance\"}[5m])) > 0",
     "legendFormat": "Sample Limit"
    },
    {
     "expr": "sum(increase(prometheus_target_scrapes_sample_duplicate_timestamp_total{instance=~\"$instance\"}[5m])) > 0",
     "legendFormat": "Duplicate Timestamp"
    },
    {
     "expr": "sum(increase(prometheus_target_scrapes_sample_out_of_bounds_total{instance=~\"$instance\"}[5m])) > 0",
     "legendFormat": "Timestamp Out of Bounds"
    },
    {
     "expr": "sum(increase(prometheus_target_scrapes_sample_out_of_order_total{instance=~\"$instance\"}[5m])) > 0",
     "legendFormat": "Sample Out of Order"
    },
    {
     "expr": "sum(increase(prometheus_treecache_zookeeper_failures_total{instance=~\"$instance\"}[5m])) > 0",
     "legendFormat": "Zookeeper"
    },
    {
     "expr": "sum(increase(prometheus_tsdb_compactions_failed_total{instance=~\"$instance\"}[5m])) > 0",
     "legendFormat": "TSDB Compactions"
    },
    {
     "expr": "sum(increase(prometheus_tsdb_head_series_not_found{instance=~\"$instance\"}[5m])) > 0",
     "legendFormat": "Series Not Found"
    },
    {
     "expr": "sum(increase(prometheus_tsdb_reloads_failures_total{instance=~\"$instance\"}[5m])) > 0",
     "legendFormat": "Reload"
    }
   ]
  },
  {
   "title": "Upness",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Upness (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "up{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Storage Memory Chunks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_chunks{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Series",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Series Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_series{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Series Created / Removed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum( increase(prometheus_tsdb_head_series_created_total{instance=~\"$instance\"}[5m]) )",
     "legendFormat": "created"
    },
    {
     "expr": "sum( increase(prometheus_tsdb_head_series_removed_total{instance=~\"$instance\"}[5m]) )",
     "legendFormat": "removed"
    }
   ]
  },
  {
   "title": "Appended Samples",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Appended Samples per Second",
   "type": "timeseries",
   "description": "Rate of total number of appended samples",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "count:samples/s" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_samples_appended_total{job=~\"$job\",instance=~\"$instance\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Sync",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Scrape Sync Total",
   "type": "timeseries",
   "description": "Total number of syncs that were executed on a scrape pool.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(prometheus_target_scrape_pool_sync_total{job=~\"$job\",instance=~\"$instance\"}) by (scrape_job)",
     "legendFormat": "{{scrape_job}}"
    }
   ]
  },
  {
   "title": "Target Sync",
   "type": "timeseries",
   "description": "Actual interval to sync the scrape pool.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(prometheus_target_sync_length_seconds_sum{job=~\"$job\",instance=~\"$instance\"}[2m])) by (scrape_job) * 1000",
     "legendFormat": "{{scrape_job}}"
    }
   ]
  },
  {
   "title": "Scrapes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "scrape_duration_seconds{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Rejected Scrapes",
   "type": "timeseries",
   "description": "Total number of rejected scrapes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(prometheus_target_scrapes_exceeded_sample_limit_total{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "exceeded sample limit"
    },
    {
     "expr": "sum(prometheus_target_scrapes_sample_duplicate_timestamp_total{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "duplicate timestamp"
    },
    {
     "expr": "sum(prometheus_target_scrapes_sample_out_of_bounds_total{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "out of bounds"
    },
    {
     "expr": "sum(prometheus_target_scrapes_sample_out_of_order_total{job=~\"$job\",instance=~\"$instance\"}) ",
     "legendFormat": "out of order"
    }
   ]
  },
  {
   "title": "Durations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average Rule Evaluation Duration",
   "type": "timeseries",
   "description": "The duration of rule group evaluations",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "1000 * rate(prometheus_rule_evaluation_duration_seconds_sum{job=~\"$job\", instance=~\"$instance\"}[5m]) / rate(prometheus_rule_evaluation_duration_seconds_count{job=~\"$job\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(handler) (rate(prometheus_http_request_duration_seconds_count{job=~\"$job\", instance=~\"$instance\"}[1m])) > 0",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Prometheus Engine Query Duration Seconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(prometheus_engine_query_duration_seconds_sum{job=~\"$job\",instance=~\"$instance\"}) by (slice)",
     "legendFormat": "{{slice}}"
    }
   ]
  },
  {
   "title": "Rule Evaluator Iterations",
   "type": "timeseries",
   "description": "Rule-group evaluations \n - total\n - missed due to slow rule group evaluation\n - skipped due to throttled metric storage",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(prometheus_evaluator_iterations_total{job=~\"$job\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(prometheus_evaluator_iterations_missed_total{job=~\"$job\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "Missed"
    },
    {
     "expr": "sum(rate(prometheus_evaluator_iterations_skipped_total{job=~\"$job\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "Skipped"
    },
    {}
   ]
  },
  {
   "title": "Notifications",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Notifications Sent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(prometheus_notifications_sent_total[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Configuration Reloads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minutes Since Successful Config Reload",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(time() - prometheus_config_last_reload_success_timestamp_seconds{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Successful Config Reload",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_config_last_reload_successful{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 },
   "targets": [
    {}
   ]
  },
  {
   "title": "GC Rate / 2m",
   "type": "timeseries",
   "description": "GC invocation durations",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(go_gc_duration_seconds_sum{instance=~\"$instance\",job=~\"$job\"}[2m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}